export {default as UserSection} from './homepage/UserSection'
export {default as PortfolioSection} from './portfolio/Portfolio'
export {default as Skills} from './portfolio/Skills'
export {default as ContactSection} from './contactUs/ContactUs'
export {default as MyEducation} from './portfolio/MyEducation'